/*
    This file is part of Primer3 porting to java (https://github.com/primer3-org/primer3)


	Copyright (c) 1996,1997,1998,1999,2000,2001,2004,2006,2007,2008
	Whitehead Institute for Biomedical Research, Steve Rozen
	(http://purl.com/STEVEROZEN/), Andreas Untergasser and Helen Skaletsky
	All rights reserved to Primer3 authors.

    Primer3 and the libprimer3 library are free software;
    you can redistribute them and/or modify them under the terms
    of the GNU General Public License as published by the Free
    Software Foundation; either version 2 of the License, or (at
    your option) any later version.

    This software is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this software (file gpl-2.0.txt in the source
    distribution); if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
package org.primer3.masker;

/**
  * input_sequence: A wrapper for input sequence. Input can be either a stream or a 
  * string variable 
  */
public class input_sequence {

	char[] sequence_string;
	
	
	public input_sequence()
	{
		
	}
	
	public input_sequence(char[] seq)
	{
		this.sequence_string = seq;
	}
	
	public static input_sequence create_input_sequence_from_file_name(
			String sequence_file_name) {
		
		
		
		input_sequence input_seq = new input_sequence();
		// sample input
		input_seq.sequence_string = 
				(
				"AGTAGTCATTATGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGTATAAGCTTTTATACGGTGAAACT\n" + 
				"GCGAATGGCTCATTAAAACAGTTATAGTTTATTTGATGGTCTCTTCTTACATGGATAACCATGGTAATTC\n" + 
				"TATGGCTAATACATGCGCAAATGCCTCCTTCTCTGGAGGGGCTGTGTTTATTAGATACAAAACCAACCCA\n" + 
				"CTTTTGTGGAGTCCTGGTGATTCATAGTAACCAAACGGATCGCATTTGGCTTCGGCCCGCGATGGATCTT\n" + 
				"TCAAGTTTCTGACCTATCAGCTTTCGACGGTAGGGTATTGGCCTACCGTGGCAGTGACGGGTAACGGGGA\n" + 
				"ATTAGGGTTCGATTCCGGAGAGGGAGCCTGAGAAACGGCTACCACATCTAAGGAAGGCAGCAGGCGCGCA\n" + 
				"AATTACCCAATGAAAACAGTTTCGAGGTAGTGACGAGAAATAACAATACAGGGCATTTTATGCTCTGTAA\n" + 
				"TTGGAATGATGGGAATGTAAAACCCTTCCAGAGTAACAATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCG\n" + 
				"GTAATTCCAGCTCCAATAGTGTATATTAGAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATTTCTGCTGT\n" + 
				"GGTCATCCGGTACCGCCCGTATGGGTGCGCACCTGGTTTGGCTCCGGCTTTCTTCCTGTAGCCGTCCGCG\n" + 
				"CTTAATTGCGTGTACTGTGTTACGGAACTTTTACTTTGAGAAAAATAGAGTGTTTCAAGCAGGCTTGTCG\n" + 
				"CCCTGAATACTTCAGCATGGAATAATAGGATAGGACCTTGGTTCTATTTTGTTGGTTTCTAGGACCAAGG\n" + 
				"TAATGATTAATAGGGACAGTTGGGGGCATTCGTATTTAACTGTCAGAGGTGAAATTCTTAGATTTGTTAA\n" + 
				"AGACGAACTACTGCGAAAGCATTTGCCAAGGATGTTTTCATTAATCAAGAACGACAGTAGGGGGTTTGAA\n" + 
				"GACGATTAGATACCGTCGTAATCTCTACCATAAACTATGCCGACTAGAGATAGGGAAATGCCTACCTTGG\n" + 
				"CTTCTCCTGCACCTCATGAGAAATCAAAGTCTCTGGGTTCTGGGGGGAGTATGGTCGCAAGGCTGAAACT\n" + 
				"TAAAGGAATTGACGGAAGGGCACCACCAGGCGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGGAAAC\n" + 
				"TCACCAGGTCCAGACATGGGAAGGATTGACAGATTGATAGCTCTTTCTTGATTCTATGGGTGGTGGTGCA\n" + 
				"TGGCCGTTCTTAGTTGGTGGAGTGATCTGTCTGGTTAATTTCGATAACGAACGAGACCTTAGCCTGCTAA\n" + 
				"ATAGGATCGGGAACTACGGTTCTCGTATCACTTCTTAGAGGGACTTTGCGTGTCTAACGCAAGGAAGTTT\n" + 
				"GAGGCAATAACAGGTCTGTGATGCCCTTAGATGTTCTGGGCTGCACGCGCGCTACACTGATGCATGCAAC\n" + 
				"GAGTTCTTGACCTTGGCCGGAAGGTCTAGGTAATCTTTTGAGTGTGCATCGTGATGGGGATAGATTATTG\n" + 
				"CAATTATTAATCTTCAACGAGGAATGCCTAGTAGGCGTAAGTCAGCAGCTTGCGCCGATTACGTCCCTGC\n" + 
				"CCTTTGTACACACCGCCCGTCGCTGCAACCGATCGGAGGGTCCTGTGAACTCAATGGACTGACCAACTCC\n" + 
				"CTTCGGGGGTTGGTCGGAAAGTTGCGTAAATAGAGCCCTCTAAAGGATGCAAAAGTCGTAACACGGTTTC\n" + 
				"CGTAGGTGAACCTGCGGAAGGATCATTCACACATTCAAAATAGTTTTGGAATGCTTCTGGGTAACATGTT\n" + 
				"TCTACCCACTACATCCAACCTCCTGATAGTTGGTTGGCCTGTTGTGGATAGTTACTGTTGTGTTTGTTCC\n" + 
				"CTTATGGCATTTCCAAGACTGTGGTCTTATAAAAAACCTCACCACAAAACCCTGTAAACTATTGATTCTT\n" + 
				"TCAGTTCCGGTTTTTTTTTTATTTAAAAAAAAAAACTGGCCCCACAACGTCTTCTTTCCTGTTAAATATT\n" + 
				"TTTTGTTTATGTTTGCAATAATCTGCGTTATGGGTGATGATGACATATTTTAAGGTTTTTTCCTTTGCGG\n" + 
				"TTTTTTGGCCGCAAAGGATATATTTATTACCTTAAATTGTTGTCCTCCTCCTTATCGCGGTTATTTCTTT\n" + 
				"CATTAAAGTAGAAAAACTTTCAGCAATGATGTCTGCTCGTGCATCGATGAAGACGCAGCGAAATGCGATA\n" + 
				"CGCATTGTGAATTGCAGATTTCAGTGAACCATCAGATTTCCGAACGCATATGGCGCTGTGGGGACTTCCC\n" + 
				"CGCAGCACGTCTGTTTCAGTGTCTTTTAAACTACACTTCAAATACACCGCCACGTTTTATAAAGAAAAAA\n" + 
				"GTGTAACGGCAGTTTTGATACTCTTGCTTGTGTCAATGAATTGTCGCTTGCATGTATTTTTTTTTTTAAA\n" + 
				"CGCTTTGCGGTATTTTTTGGGTGTCGATATCTGTGATGGTGTCGTCTCCTTAAATTTGTTGAATTCTACA\n" + 
				"TGTTTCATGCCTTCTCTTCTGGCACTGTGTGTTAGAAGTGAAGGTATTGTTGTTGTTGTATGAATGGCTT\n" + 
				"TTAATAATACAAACCCATATCCTTTCTTCTCCTGAAAGAGATAAGGTGGATGGATTATAAATATATTCTC\n" + 
				"CTTATGTATATCTCATATTTTGGGAGTTTGGTGAAGAGCTGTGATGGCGTTGTGTATGGATTAAGCATTA\n" + 
				"TTCTTTGGTTGGTGATGATGAAAAGACAGACACTTCTGTCACACCGTCGTCGCCCGCTAGATGATAATGC\n" + 
				"TTTTCTCCTATCATATAAGCCACAAGCAAAGATACCATTATATAAAGGAATGAGTATGTTTTATTTAGCC\n" + 
				"ATAAAAAAGAAATACAACAACAAGTCAGAATAATATAGCAACGCAATCAAAAGAGAAGAGCGTATTATTA\n" + 
				"TAACGATTGTTATATATTATTTATTGCTCTCTCATATATCTATCTAGACCTGAAATCAGTCGAGGATACC\n" + 
				"CGCTGAATTTAAGCATATTATTAAGCGGAGGAAAAGAAAATAACTATGATTCCCTCAGTAACGGCGAGTG\n" + 
				"AAGAGGGAGGTGCTCAAAGTGAAAATCGTGGTACCTCTTATGGTACCGCGAGTTGTAGCCTCTAGAGGCG\n" + 
				"T"
				).toCharArray();

		
		
		
		return input_seq;
	}
	 
	

}