package com.primer3.masker;

/**
  * input_sequence: A wrapper for input sequence. Input can be either a stream or a 
  * string variable 
  */
public class input_sequence {

	char[] sequence_string;
	
	
	public input_sequence()
	{
		
	}
	
	public input_sequence(char[] seq)
	{
		this.sequence_string = seq;
	}
	
	public static input_sequence create_input_sequence_from_file_name(
			String sequence_file_name) {
		
		
		
		input_sequence input_seq = new input_sequence();
		// sample input
		input_seq.sequence_string = 
				(
				"AGTAGTCATTATGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGTATAAGCTTTTATACGGTGAAACT\n" + 
				"GCGAATGGCTCATTAAAACAGTTATAGTTTATTTGATGGTCTCTTCTTACATGGATAACCATGGTAATTC\n" + 
				"TATGGCTAATACATGCGCAAATGCCTCCTTCTCTGGAGGGGCTGTGTTTATTAGATACAAAACCAACCCA\n" + 
				"CTTTTGTGGAGTCCTGGTGATTCATAGTAACCAAACGGATCGCATTTGGCTTCGGCCCGCGATGGATCTT\n" + 
				"TCAAGTTTCTGACCTATCAGCTTTCGACGGTAGGGTATTGGCCTACCGTGGCAGTGACGGGTAACGGGGA\n" + 
				"ATTAGGGTTCGATTCCGGAGAGGGAGCCTGAGAAACGGCTACCACATCTAAGGAAGGCAGCAGGCGCGCA\n" + 
				"AATTACCCAATGAAAACAGTTTCGAGGTAGTGACGAGAAATAACAATACAGGGCATTTTATGCTCTGTAA\n" + 
				"TTGGAATGATGGGAATGTAAAACCCTTCCAGAGTAACAATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCG\n" + 
				"GTAATTCCAGCTCCAATAGTGTATATTAGAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATTTCTGCTGT\n" + 
				"GGTCATCCGGTACCGCCCGTATGGGTGCGCACCTGGTTTGGCTCCGGCTTTCTTCCTGTAGCCGTCCGCG\n" + 
				"CTTAATTGCGTGTACTGTGTTACGGAACTTTTACTTTGAGAAAAATAGAGTGTTTCAAGCAGGCTTGTCG\n" + 
				"CCCTGAATACTTCAGCATGGAATAATAGGATAGGACCTTGGTTCTATTTTGTTGGTTTCTAGGACCAAGG\n" + 
				"TAATGATTAATAGGGACAGTTGGGGGCATTCGTATTTAACTGTCAGAGGTGAAATTCTTAGATTTGTTAA\n" + 
				"AGACGAACTACTGCGAAAGCATTTGCCAAGGATGTTTTCATTAATCAAGAACGACAGTAGGGGGTTTGAA\n" + 
				"GACGATTAGATACCGTCGTAATCTCTACCATAAACTATGCCGACTAGAGATAGGGAAATGCCTACCTTGG\n" + 
				"CTTCTCCTGCACCTCATGAGAAATCAAAGTCTCTGGGTTCTGGGGGGAGTATGGTCGCAAGGCTGAAACT\n" + 
				"TAAAGGAATTGACGGAAGGGCACCACCAGGCGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGGAAAC\n" + 
				"TCACCAGGTCCAGACATGGGAAGGATTGACAGATTGATAGCTCTTTCTTGATTCTATGGGTGGTGGTGCA\n" + 
				"TGGCCGTTCTTAGTTGGTGGAGTGATCTGTCTGGTTAATTTCGATAACGAACGAGACCTTAGCCTGCTAA\n" + 
				"ATAGGATCGGGAACTACGGTTCTCGTATCACTTCTTAGAGGGACTTTGCGTGTCTAACGCAAGGAAGTTT\n" + 
				"GAGGCAATAACAGGTCTGTGATGCCCTTAGATGTTCTGGGCTGCACGCGCGCTACACTGATGCATGCAAC\n" + 
				"GAGTTCTTGACCTTGGCCGGAAGGTCTAGGTAATCTTTTGAGTGTGCATCGTGATGGGGATAGATTATTG\n" + 
				"CAATTATTAATCTTCAACGAGGAATGCCTAGTAGGCGTAAGTCAGCAGCTTGCGCCGATTACGTCCCTGC\n" + 
				"CCTTTGTACACACCGCCCGTCGCTGCAACCGATCGGAGGGTCCTGTGAACTCAATGGACTGACCAACTCC\n" + 
				"CTTCGGGGGTTGGTCGGAAAGTTGCGTAAATAGAGCCCTCTAAAGGATGCAAAAGTCGTAACACGGTTTC\n" + 
				"CGTAGGTGAACCTGCGGAAGGATCATTCACACATTCAAAATAGTTTTGGAATGCTTCTGGGTAACATGTT\n" + 
				"TCTACCCACTACATCCAACCTCCTGATAGTTGGTTGGCCTGTTGTGGATAGTTACTGTTGTGTTTGTTCC\n" + 
				"CTTATGGCATTTCCAAGACTGTGGTCTTATAAAAAACCTCACCACAAAACCCTGTAAACTATTGATTCTT\n" + 
				"TCAGTTCCGGTTTTTTTTTTATTTAAAAAAAAAAACTGGCCCCACAACGTCTTCTTTCCTGTTAAATATT\n" + 
				"TTTTGTTTATGTTTGCAATAATCTGCGTTATGGGTGATGATGACATATTTTAAGGTTTTTTCCTTTGCGG\n" + 
				"TTTTTTGGCCGCAAAGGATATATTTATTACCTTAAATTGTTGTCCTCCTCCTTATCGCGGTTATTTCTTT\n" + 
				"CATTAAAGTAGAAAAACTTTCAGCAATGATGTCTGCTCGTGCATCGATGAAGACGCAGCGAAATGCGATA\n" + 
				"CGCATTGTGAATTGCAGATTTCAGTGAACCATCAGATTTCCGAACGCATATGGCGCTGTGGGGACTTCCC\n" + 
				"CGCAGCACGTCTGTTTCAGTGTCTTTTAAACTACACTTCAAATACACCGCCACGTTTTATAAAGAAAAAA\n" + 
				"GTGTAACGGCAGTTTTGATACTCTTGCTTGTGTCAATGAATTGTCGCTTGCATGTATTTTTTTTTTTAAA\n" + 
				"CGCTTTGCGGTATTTTTTGGGTGTCGATATCTGTGATGGTGTCGTCTCCTTAAATTTGTTGAATTCTACA\n" + 
				"TGTTTCATGCCTTCTCTTCTGGCACTGTGTGTTAGAAGTGAAGGTATTGTTGTTGTTGTATGAATGGCTT\n" + 
				"TTAATAATACAAACCCATATCCTTTCTTCTCCTGAAAGAGATAAGGTGGATGGATTATAAATATATTCTC\n" + 
				"CTTATGTATATCTCATATTTTGGGAGTTTGGTGAAGAGCTGTGATGGCGTTGTGTATGGATTAAGCATTA\n" + 
				"TTCTTTGGTTGGTGATGATGAAAAGACAGACACTTCTGTCACACCGTCGTCGCCCGCTAGATGATAATGC\n" + 
				"TTTTCTCCTATCATATAAGCCACAAGCAAAGATACCATTATATAAAGGAATGAGTATGTTTTATTTAGCC\n" + 
				"ATAAAAAAGAAATACAACAACAAGTCAGAATAATATAGCAACGCAATCAAAAGAGAAGAGCGTATTATTA\n" + 
				"TAACGATTGTTATATATTATTTATTGCTCTCTCATATATCTATCTAGACCTGAAATCAGTCGAGGATACC\n" + 
				"CGCTGAATTTAAGCATATTATTAAGCGGAGGAAAAGAAAATAACTATGATTCCCTCAGTAACGGCGAGTG\n" + 
				"AAGAGGGAGGTGCTCAAAGTGAAAATCGTGGTACCTCTTATGGTACCGCGAGTTGTAGCCTCTAGAGGCG\n" + 
				"T"
				).toCharArray();

		
		
		
		return input_seq;
	}
	 
	

}